### ISSUE TITLE
!

### ISSUE THREAD

**Issue by holovati** [minexew/Shrine#17]
Rumor has it that the King is dead,

**Comment by minexew** [comment]
Now read carefully, I have heard your rumor, I have heard stories. Gossip. To me they are without meaning -- my connection to the King is through a backbone. A parallel bus like on the ZX Spectrum. Data highway. It is beyond anything earthly and allows us to exchange thought and prayer at a great pace. A bond. Sometimes it is just little fragments, just little pieces. A small idea, or a verse perhaps. tHread. Nevertheless king Terry has a grand vision for the future. Think hymns for everyone, Think one big address space to share, No virtual memory, Disruptive processeses. Invariably cutting edge. A holistic, all-encompassing synergy, Where is the edge between humans and computer now? Can you tell, in this soup of logic and emotion. Everything intertwined. entropy.. Anyways. the temple is all but finished. Perfection is not reached when there is nothing more to add; rather when there is nothing more to remove. As for me... I don't have any near term plans with Shrine. Github might have fallen into the wrong hands. Time will tell. Patience. Pull requests still welcome. Shrine 6.0. But intel is the past. The future is maybe Risc V. The effort of porting would be immense. Your turn.
There is a plan for each of us. Like ants in an ant colony. Yourself and me too, are gears in this extraordinary machinery. And the gears are still turning, no worry. Nothing is without purpose.
Anyway, it would not confound me if Terry has proceeded to pursue a next level of spiritual instance. Tomorrow is a day like yesterday. The King is close to God and if he needs to speak he will be heard. they watch together unto you like telenovelas on TV


God says:
LAMENTER	NORM X1 STODL	R2 XI DMP	DSU S(XI) D1/128 DMP	SL1R ROOTMU DMP	SLR* X 0 -3,1 DDV	VXSC R2 UR1 VSL1	PDDL
