### ISSUE TITLE
Remove networking

### ISSUE THREAD

**Issue by nukeop** [minexew/Shrine#2]
It is said in the Temple OS charter that there shall be no networking, so that malware is not an issue:
http://www.templeos.org/Wb/Doc/Charter.html

God says...

> naughty It_grieves_me ahh absetively_posilutely freak bank ingrate sex spunky What_are_you_doing_Dave shucks joking application a_flag_on_that_play stunning You_know downer I'm_not_sure run_away Icarus skills bad_ol_puddytat be_happy what_was_I_thinking dang_it game_over heathen so_he_sess it_figures IMHO hilarious how_do_I_put_this

**Comment by minexew** [comment]
delete this.

God says...
> Pakistan chummier Riemann advertise claim's Vitus tinder hospitalization's 
oneness ocular appellant's Almighty Persians Coke's hawk's Tongan backbiting 
penknife coincide Opel's bumbler brunet's cambiums elaborateness Haitians drip's 
compliance gaits mint's Josefa preserving glum cameos researched Daniel's 
anchorites Zoroastrianisms Phekda's inheriting quadriphonic trimmed chiming 
freeloading

**Comment by alureon** [comment]
God did not ban networking (said by Terry himself).
https://www.reddit.com/r/TempleOS_Official/comments/2pzdy6/can_there_be_networking/cn1kshe/

God says...
>Boo you're_welcome chill_out no_you_cant joke do_you_like_it hot_air let's_see ba_ha wrath I'm_good_you_good BBC happy_happy_joy_joy you_see_the_light you're_so_screwed God scorning one_more_time potentially small_talk hypocrite pwned just_between_us genius church ipod spunky What begs_the_question nasty hang_in_there daunting
