### ISSUE TITLE
Failed to run make-dist.py

### ISSUE THREAD

**Issue by megascrapper** [minexew/Shrine#20]
I was running the command `./make-dist.py TOS_Distro.ISO Shrine ~/shrine.img` and expected the `Shrine-HEAD.iso` file to be outputted. 

But as I run the command, this message appears:
```
Applied 2 patches, 669 bytes total
qemu-system-x86_64: -serial tcp::7770,server: info: QEMU waiting for connection on: disconnected:tcp::::7770,server
> ?
```
meanwhile, TempleOS boots in the background and it just stuck there for a few minutes before it errors out and shows this message:
```
qemu-system-x86_64: terminating on signal 15 from pid 6804 (<unknown process>)
Traceback (most recent call last):
  File "./make-dist.py", line 124, in <module>
    os.path.join(AUTO_INSTALL_PATH, 'install.script'), AUTO_INSTALL_TIMEOUT)
  File "./make-dist.py", line 106, in run_qemu_and_mfa
    wait_for_subprocess(mfa, timeout)
  File "./make-dist.py", line 83, in wait_for_subprocess
    raise Exception('Subprocess didn\'t finish in time')
Exception: Subprocess didn't finish in time
```

# Additional info
OS: macOS 10.13.6
Python version: 2.7.10 and 3.7.0
QEMU version: 3.0.0

Screenshot of TempleOS wile running
![](https://i.imgur.com/2qFC4PQ.png)

**Comment by etisdew** [comment]
I also concur that seems very suspicious.

**Comment by minexew** [comment]
Interference between Shrine's TCP/IP stack and the installation process is extremely unlikely, because at this point in the installation the guest OS is still nearly clean TempleOS (all the changes get pulled in *after* mfa connects to a backdoor in the guest OS)

**Comment by etisdew** [comment]
I think we're just running into this eval `
if not args.skip_tos_install:`, @megascrapper thanks for being so active, what do you think?

**Comment by etisdew** [comment]
@megascrapper @minexew is this just a missing flag situation for initial iso and a non-issue allowing the issue to be closed? Or is this still blocking?

**Comment by minexew** [comment]
Installation of TempleOS is a necessary part of the build process, so no, the default should *not* be to skip it.

**Comment by zaklaus** [comment]
Were you able to resolve this issue?

**Comment by minexew** [comment]
Shrine has got a new build system now, so we can obliterate this issue to hell.
