### ISSUE TITLE
Color schemes

### ISSUE THREAD

**Issue by flowac** [minexew/Shrine#21]
I noticed that you are changing the colors by changing the default color definitions (eg: redefining white or black).
How could I change the default foreground and background by specifying a color like FG=GREEN or BG=RED?
Terry's help files mentioned something about global variables but I couldn't figure out where they are stored or how to change them.

I managed to change the color of the status bar at the top (showing date and CPU load) by changing /Adam/WallPaper, but I would like to change the color of the terminal and the text editor.

**Comment by minexew** [comment]
Can you give a more specific example? I kinda understand what you're getting at. But you need to keep in mind that you're working in a display mode with just 16 colors.
If you need to temporarily change FG/BG color, you can do it like this:

    "$FG,8$Welcome to $FG,5$Lambda Shell$FG,8$!\n";
    "Type $FG,0$intro$FG,8$ for a quick introduction.\n\n";

As for re-assigning the defaults, I wouldn't really know where to start looking.
