### ISSUE TITLE
Is Shrine OS based ( ;) ) on the latest Temple OS version?

### ISSUE THREAD

**Issue by informer2016** [minexew/Shrine#22]
Dear @minexew , first of all thank you very much for your wonderful Shrine OS project! Please tell, have you merged all the latest available updates of TempleOS _(21-Nov-2017)_ into the Shrine OS ? By looking at your commits I see that you have updated your TempleOS directory to 21-Nov-2017, but it is unclear to me whether all the updates which happened after you forked TempleOS into Shrine, have also been merged into the Shrine sources

**Comment by minexew** [comment]
Shrine is not really a fork, but a set of patches and programs. Nothing is copied from upstream TempleOS into this repo, the code is merged at Shrine build time.

**Comment by minexew** [comment]
So yeah, whatever is the TempleOS submodule, is being used.
