### ISSUE TITLE
Why Shrine_v505.iso weights much less than TOS_Distro.ISO ?  3.7 MB vs 16.5 MB

### ISSUE THREAD

**Issue by informer2016** [minexew/Shrine#23]
@minexew I wonder if its just better compression _(although 7zip could compress it further below 2.8MB)_ or some stuff has been removed? If yes - what stuff?

**Comment by minexew** [comment]
I believe it's just the Bible. Reference: https://github.com/minexew/Shrine/blob/master/Shrine/mkdist.script#L4

**Comment by informer2016** [comment]
@minexew I'm trying to find out if it is possible to somehow fit Shrine OS to 2.88MB double floppy. Not a physical floppy, "virtual" of course: I could Seasily add any floppy to coreboot+SeaBIOS, and then you'd see it as a boot entry! :wink: Would it be cool to be able to launch your ShrineOS right from a BIOS chip?

**Comment by informer2016** [comment]
@minexew Happy coming New Year ! :christmas_tree: :santa: :gift:

**Comment by samboy** [comment]
I am curious why the Bible is so big, though. A full Bible (either Catholic or Protestant; the Apocrypha does not make that much of a difference) is about 5 to 6 megabytes in size.

**Comment by minexew** [comment]
Feel free to discuss this further, but at this point, there is no actionable issue here
