### ISSUE TITLE
Could Shrine fit on a 1.44MB or 2.88MB floppy?

### ISSUE THREAD

**Issue by informer2016** [minexew/Shrine#26]
Good day, @minexew and @tim241 . Please tell, could Shrine fit on a 1.44MB or 2.88MB floppy? Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful ShrineOS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

So far I see 3.67 MB ISO image at your Shrine releases, but could it be somehow transformed into a floppy, maybe not 1.44MB but an 2.88MB one?

**Comment by minexew** [comment]
I don't know. Why don't you find out? :wink:

**Comment by informer2016** [comment]
@minexew good question :wink:   well, I am not familiar with Shrine codebase, so don't know the candidates like Bible which could be removed without losing much in order to shrink Shrine from 3.7MB to at least 2.88MB. Also my skills as a programmer are quite low to be honest, but I'm really good at testing and writing detailed reports, so if you could make a 2.88MB floppy out of ShrineOS - then I could test it and its' internals and submit a lot of detailed issues. For example, at the moment I am also helping to MichalOS - https://sourceforge.net/p/michalos/tickets/ - submitted 33 tickets and helped to close 20+ by testing a lot of debug builds as a part of this coreboot opensource BIOS . So if you could make such a floppy for me I will try my best to pay it off

**Comment by minexew** [comment]
I understand.
To put it simply and honestly, this is not an issue that I personally care about. So I'm afraid you're on your own.

**Comment by informer2016** [comment]
@minexew Sadly this version above - hangs after printing out InitAllBlkDevs. More info here - https://github.com/Francesco149/TempleOSGit/issues/3 . Maybe I'll try to package it as a floppy when I'd have more free time

**Comment by minexew** [comment]
LMK if you ever get around to working on this and we can re-open the issue.

**Comment by informer2016** [comment]
@minexew Sadly I've to admit I don't have enough free time to work on this
