### ISSUE TITLE
Package server down

### ISSUE THREAD

**Issue by 143mailliw** [minexew/Shrine#28]
The package server's domain name expired and the pkg command no longer works.

**Comment by minexew** [comment]
Hi, first of all, thanks for reporting this.

However, I'm not seeing any issues with the package server.
http://shrineupd.clanweb.eu/packages/packages.list downloads just fine.
Could you share a screenshot of the error you're getting in Shrine?

**Comment by 143mailliw** [comment]
Huh, seems to work now. Weird.
