### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DVD668** [minexew/Shrine#31]
Where is the license?...
many users (including me) will refuse to use it if they don't know the terms and conditions in with the software is released

Thanks in advance

**Comment by minexew** [comment]
It is what I call the "2-clause CIA license":
1. If you ARE NOT in control of the GitHub account "DVD668" (https://github.com/DVD668), you can consider this project a public domain work and apply any and all rights granted by that status.
2. If you ARE in control of said account, you may not use this code in any way.
