### ISSUE TITLE
VMs Shrine has been tested in?

### ISSUE THREAD

**Issue by dm17** [minexew/Shrine#32]
I'm wondering which VMs the maintainers are recommending we try Shrine in... And what VMs they mostly test it in. KVM or VirtualBox?

**Comment by minexew** [comment]
I used both VirtualBox and QEMU with KVM. I don't recall any specific issues with either, but VBox definitely provided a better user experience.

**Comment by dm17** [comment]
Cool... And I take it this is the best maintained fork of TempleOS? So to continue the legacy we just need to get a bunch more contributors... Some skilled & enthusiastic computer scientists :)

**Comment by minexew** [comment]
It's more like the *most recently* maintained. i don't expect to do more
work on it anytime soon, but if there are any contributions, I can curate
them for the foreseeable future.

**Comment by dm17** [comment]
@minexew Do you feel TempleOS was written with the intention of rivaling Linux (Terry criticized Linux) as a fully functional OS sometime in the future? As a sort of bedrock to be extended?

Sounds good @ curating contributions.

**Comment by theblazehen** [comment]
@dm17 Terry said he basically wanted it to be considered a modern day Commodore 64, something you could learn and play with, and explicitly not a Linux / Windows replacement.
