### ISSUE TITLE
Revive this please.

### ISSUE THREAD

**Issue by xslendix** [minexew/Shrine#33]

**Comment by minexew** [comment]
Please do!

**Comment by Lartu** [comment]
Yes!

**Comment by tosrevive** [comment]
I am willing to work on reviving this, I actually just rebuilt my Shrine ISO yesterday and have hacked its build process a bit.  It would be really great if people would help round up all the Temple OS related Apps and Temple OS based operating systems they know of so we have a centralized place to keep track of them and so they don't disappear.

I setup some repositories to keep track of stuff:

Temple OS applications and drivers:
https://github.com/tosrevive/TOSApps

Temple OS based operating systems:
https://github.com/tosrevive/TOSBasedOSs

I would appreciate help rounding up all the Apps people made for Temple OS so we can keep track of them.  It would be especially great if someone who has a local copy or mirror of the code which was located at https://devhub.io/search?keyword=tramplersheikhs would upload it to github.  I'm especially interested in the web browser uriel, the terminal application templeterm and the UEFI boot loader templeos-uefi.  If you have these file or links to other Apps please either make a pull request to put them as a sub module in https://github.com/tosrevive/TOSApps or if you don't know how, let me know where the code is and I'll do it.

On a Shrine related note, is there any chance you (or anyone?) can send me the Shrine package manager related files which where hosted at http://shrineupd.clanweb.eu/packages so I can try to find new hosting for them?  If someone could please dump them in a git repo or get them to me via any other method that would also be greatly appreciated.

I'm also interested in getting C code running inside Temple OS and HolyC code running outside of Temple OS.  To that end I've created two more repositories.

For going from ASM/HolyC to C/C++ I'm going to put stuff here:
https://github.com/tosrevive/HolyC2C
I've done a bit of work on this which I'll eventually upload.  I've looked into this quite a bit and there are various reasons this is quite difficult such as some functions are pure assembly that need to be manually translated and the HolyC compiler knows about function/symbol names at runtime which allows for the black magic of calling functions without the () or parameters.  If you've translated any of his assembly code functions to C it would also be great to put it here.  I've done a bit of translating I'll put in here eventually when I clean it up.

For going from C/C++ to HolyC or for code which enables running other languages inside Temple OS, I'm going to put stuff here:
https://github.com/tosrevive/C2HolyC
For those interested in this, there is a very awesome project described here:
https://www.jwhitham.org/2015/07/porting-third-party-programs-to-templeos.html

Again if you have anything that fits in any of these buckets, please share it!

**Comment by minexew** [comment]
Give me a few days, you shall have it!

**Comment by tosrevive** [comment]
Also you might be interested in my hack to the Temple OS boot loader.  With it you can fully automate your buils script and not have to press 1 to boot the C drive.  The relevant to
Adam/Opt/Boot/BootMHD2.HC is here:
https://github.com/tosrevive/ShrineTextMode/commit/f7fbc2420e9664099a436501d667737b8c58db51

**Comment by minexew** [comment]
Sorry for the delay.
Mirror of shrineupd: https://github.com/minexew/Shrine/releases/download/dummytag/zaloha_shrineupd.clanweb.eu_web_2019-08-28-212301.zip
Helper scripts i used to maintain it: https://gist.github.com/minexew/96851a3b8e93f04dad54b22c524faa51

**Comment by tosrevive** [comment]
Thanks, got it.  I'll setup some web hosting and get it working again and then I'll make a pull request.

**Comment by tosrevive** [comment]
I've setup hosting for the packages and made a pull request that fixes the package manager to point to the new link.  If you want to test it before a new Shrine release happens, just modify your Pkg.HC like what is done in the pull request.

**Comment by xslendix** [comment]
Why not make temple os also compatible again with real hardware while we are still at codin templeos.

**Comment by xslendix** [comment]
I'm working on a new package manager for TOS. The only thing is, I need help with snailnet since it has problems. See #35 for details on the problem. The server seems to be working fine, until then, i will start working on a prototype in python3.

**Comment by minexew** [comment]
Closing for now, hope erryone's cool with that.
