### ISSUE TITLE
Make PCI devices work with >= 4 GB RAM

### ISSUE THREAD

**Issue by minexew** [minexew/Shrine#4]
Perhaps easy? Maybe needs ACPI? Who knows.

Any help with this would be greatly appreciated.

**Comment by tramplersheikhs** [comment]
This may not be an acceptable solution, but it appears to work fine in this case.

tramplersheikhs/Shrine@0f69750

**Comment by nukeop** [comment]
You are increasing your punishment. You're in for a very rude shock, LOL. 

God said I get to trample the CIA shortly. The CIA dream is a world of big-eyed dumb emasculated nigger cattle with no guns and no compilers with code in cloud GitHub under lock and key

**Comment by minexew** [comment]
Fantastic!
