### ISSUE TITLE
Multiple software repositories?

### ISSUE THREAD

**Issue by rem-pai** [minexew/Shrine#40]
What about adding ability to add custom repositories to package manager by entering their URLs to some file? It would be awesome.

**Comment by minexew** [comment]
First of all, sorry, I have no idea why I missed the notification for this issue.

Secondly, pull requests are welcome :) in true spirit of TempleOS, the file would probably be Pkg.HC directly

**Comment by fkwa** [comment]
> First of all, sorry, I have no idea why I missed the notification for this issue.
It's ok. I didn't get my notification too)

> pull requests are welcome
I wish I could implement this. But I'm not familiar with HolyC. I just wanted to do a repo with web interface like npm ^^

**Comment by minexew** [comment]
For playing around, you can literally just change the repository URL in Pkg.HC.

Have you been able to reverse-engineer the structure of the repository (which is extremely simple)? Or do I need to write some sort of specification?

**Comment by minexew** [comment]
Hi @rem-pai, is this issue still valid?

**Comment by celestora** [comment]
No, you can close it now.
Oh, I can close my issues myself…
