### ISSUE TITLE
Add favicon.ico to Shrine's site

### ISSUE THREAD

**Issue by DGKSK8LIFE** [minexew/Shrine#45]

**Comment by TomJansen** [comment]
![shrine favico idea](https://user-images.githubusercontent.com/2716208/81953189-ac6d4080-9607-11ea-9e9a-1cb99c53f1af.png)
 I tried to to make a shrine, with the sword of TempleOS in front of it. Let me know what you think.

**Comment by DGKSK8LIFE** [comment]
> ![shrine favico idea](https://user-images.githubusercontent.com/2716208/81953189-ac6d4080-9607-11ea-9e9a-1cb99c53f1af.png)
> I tried to to make a shrine, with the sword of TempleOS in front of it. Let me know what you think.
> 
> PS: this file is in the Public Domain

that sounds super cool; would def be an honor to terry

**Comment by minexew** [comment]
It's fucking awful, and I love it.

Done.

**Comment by DGKSK8LIFE** [comment]
> It's fucking awful, and I love it.
> 
> Done.

nice

**Comment by DGKSK8LIFE** [comment]
> It's fucking awful, and I love it.
> 
> Done.

 can I close now?
