### ISSUE TITLE
Why is this mostly not in HolyC?

### ISSUE THREAD

**Issue by Leprawel** [minexew/Shrine#46]
Why the decision to write Shrine in C? Or is it just github counting HolyC as C?

**Comment by minexew** [comment]
Most of Shrine's code dates to before GitHub had HolyC highlighting, so the files contain a vim-style  tag declaring it as C:

`// vim: set ft=c:`

At this point, it is probably only a matter of removing this line and then the language will be picked up correctly. I just never cared enough

**Comment by Nakilon** [comment]
I would not close this issue until tags are gone.
