### ISSUE TITLE
GnuTools/SSH?

### ISSUE THREAD

**Issue by ParzivalWolfram** [minexew/Shrine#47]
Can we add GnuTools and SSH packages? I'd do it myself but i'm retarded.

**Comment by minexew** [comment]
Actionable course of action:

- stop being retarded
- do it yourself (to the benefit of everyone)
- bonus: you're no longer retarded!

**Comment by ParzivalWolfram** [comment]
Oh. I see. You're one of those types.

Never mind, then.

**Comment by tecfu** [comment]
Excellent

**Comment by xslendix** [comment]
he's right doe
