### ISSUE TITLE
shrine.systems not available

### ISSUE THREAD

**Issue by fwdekker** [minexew/Shrine#61]
Hi! I just wanted to inform you that https://shrine.systems is not currently accessible. When visiting the website, Firefox gives me a `SSL_ERROR_BAD_CERT_DOMAIN` because the cert is registered to `c84322.sgvps.net`. Ignoring that message brings me to a page saying "This is the default server vhost" without anything else on the website. Perhaps something went wrong with the configuration?

**Comment by minexew** [comment]
It was a DNS fuckup. Might take a few hours to come back.

Thanks for reporting.

**Comment by minexew** [comment]
Btw, if someone would be interested in taking over the maintenance of the website, I would not be insulted...

(I can keep paying the bills for the foreseeable future)

**Comment by slendidev** [comment]
> Btw, if someone would be interested in taking over the maintenance of the website, I would not be insulted...
> 
> (I can keep paying the bills for the foreseeable future)

I'm in :^)

Also PR may now be closed.

**Comment by fwdekker** [comment]
The website is available for me now, so I think the issue can be closed. Unless you want to keep it open to discuss taking over maintenance.

**Comment by und3f** [comment]
It is not available, seems web server is down
```
$ curl shrine.systems
curl: (7) Failed to connect to shrine.systems port 80 after 231 ms: Couldn't connect to server
```

**Comment by minexew** [comment]
Should be back up now. it was some nginx/selinux bullshit

god i hate computers

**Comment by fwdekker** [comment]
The website is up now so I'll close the issue :+1:
